spring:
  application:
    name: doan
  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:

    password: 123
    uris: http://localhost:9200
    username: elastic
  datasource:
    url: jdbc:mysql://localhost/doan
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    lazy-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 25842139974-c5f6jqqdbgudj1oik22517peir6r4ebm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
                - email
                - profile
  mail:
    host: smtp.gmail.com
    username: anhla12h@gmail.com
    password: pith klrm dhhd edhm
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
        security: DEBUG
        cache: info

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/


indexer:
  batch_size: 50
  threads: 4
  transaction_timeout: 3600  # in seconds
  optimize_after_purge: true
  purge_all_on_start: false



#//pith klrm dhhd edhm
